name: "Elephant OSS - Publish elixir packages to hex.pm"
description: "Publish elixir packages to hex.pm"
author: "elephantoss"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "package"
  color: "purple"
